namespace AnálisisCodigo.Sintaxis
{
    /// <summary>
    /// This are the token that the lexer will build, aso they are the leaves of the tree generated by the parser.
    /// </summary>
    public class Token : Nodo
    {
        public Token(Tipo tipo, int position, string text, object value)
        {
            this.tipo = tipo;
            Position = position;
            Text = text;
            Value = value;
        }

        public override Tipo tipo { get; }
        public int Position { get; }
        public string Text { get; }
        public object Value { get; }

        public TextSpan Span => new TextSpan(Position, Text.Length);
        public override IEnumerable<Nodo> Hijos()
        {
            return Enumerable.Empty<Nodo>();
        }

        public override object value
        {
            get
            {
                if (Value is null)
                {
                    return String.Empty;
                }
                return Value;
            }
        }
    }
}